import { SICSearchComponent } from './../../internal/search/iCABSSSICSearch.component';
import { AUPostcodeSearchComponent } from './../../internal/grid-search/iCABSAAUPostcodeSearch';
import { MarktSelectSearchComponent } from './../../internal/search/iCABSMarktSelectSearch.component';
import { PostCodeSearchComponent } from './../../internal/search/iCABSBPostcodeSearch.component';
import { RegulatoryAuthoritySearchComponent } from './../../internal/search/iCABSBRegulatoryAuthoritySearch.component';
import { PNOLPremiseSearchGridComponent } from './../../internal/grid-search/iCABSAPNOLPremiseSearchGrid.component';
import { ScreenNotReadyComponent } from './../../../shared/components/screenNotReady';
import { CustomerTypeSearchComponent } from './../../internal/search/iCABSSCustomerTypeSearch';
import { PestNetOnLineLevelSearchComponent } from './../../internal/search/iCABSBPestNetOnLineLevelSearch.component';
// import { InvoiceGroupSearchComponent } from './../../internal/search/iCABSAInvoiceGroupSearch.component';
import { InvoiceGroupGridComponent } from './../../internal/grid-search/iCABSAInvoiceGroupGrid';
import { SalesAreaSearchComponent } from './../../internal/search/iCABSBSalesAreaSearch.component';
import { PremiseSearchComponent } from './../../internal/search/iCABSAPremiseSearch';
import { ContractSearchComponent } from './../../internal/search/iCABSAContractSearch';
import { EmployeeSearchComponent } from '../../../app/internal/search/iCABSBEmployeeSearch';
import { MntConst } from '../../../shared/services/riMaintenancehelper';

export class UiControls {
    public controls = [
        { name: 'ContractNumber', disabled: false, type: MntConst.eTypeCode, required: false, value: '', primary: true },
        { name: 'PremiseNumber', disabled: false, type: MntConst.eTypeAutoNumber, required: false, value: '', primary: true },
        { name: 'ContractTypeCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '', primary: true },
        { name: 'AccessFrom1', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom10', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom2', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom3', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom4', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom5', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom6', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom7', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom8', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessFrom9', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo1', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo10', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo2', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo3', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo4', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo5', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo6', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo7', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo8', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccessTo9', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'AccountName', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'AccountNumber', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'AdditionalActionComments', disabled: false, type: '', required: false, value: '' },
        { name: 'AdditionalComments1', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'AdditionalComments2', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'AdditionalLocations', disabled: false, type: '', required: false, value: '' },
        { name: 'AllowAllTasks1', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks10', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks2', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks3', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks4', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks5', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks6', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks7', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks8', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AllowAllTasks9', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'AnyPendingBelow', disabled: true, type: MntConst.eTypeText, required: false, value: '' }, //??
        { name: 'AppointmentDetailDesc', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'AppointmentRequiredInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'AssociatedToPremiseNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'BadDebtAccount', disabled: false, type: '', required: false, value: '' },
        { name: 'CICFWOReq', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'CICFWOSep', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'CICResponseSLA', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'CICustRefReq', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'CIFirstSLAEscDays', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'CIRWOReq', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'CISubSLAEscDays', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'ClientReference', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'ContractName', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'CreateNewInvoiceGroupInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'CreateNewSRA', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'CustomerAvailTemplateDesc', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'CustomerAvailTemplateID', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'CustomerInfoAvailable', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'CustomerTypeCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'CustomerTypeDesc', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'DisableList', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'DisplayQty', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'DrivingChargeInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'DrivingChargeValue', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'EmployeeCode1', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode10', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode2', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode3', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode4', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode5', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode6', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode7', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode8', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeCode9', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'EmployeeSurname1', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname10', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname2', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname3', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname4', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname5', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname6', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname7', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname8', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EmployeeSurname9', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'EnvironmentalRestrictedAreaInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'EnvironmentalRestrictedAreaText', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'ErrorMessageDesc', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'Friday', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'GblSRAAdditionalSRA', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'GblSRAAdditionalSRADocReftext', disabled: false, type: '', required: false, value: '' },
        { name: 'GblSRADesc', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'GblSRATypeCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'GPSCoordinateX', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'GPSCoordinateY', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'GuaranteeNumberBedrooms', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'HyperSensitive', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'InactiveEffectDate', disabled: true, type: MntConst.eTypeDate, required: false, value: '' }, //??
        { name: 'InitialTreatmentInstructions', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'InvoiceGroupDesc', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'InvoiceGroupNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'InvoiceNarrativeText', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'InvoiceSuspendInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'InvoiceSuspendText', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'LabourCost', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'LabourValue', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'LinkedToContractName', disabled: true, type: '', required: false, value: '' },
        { name: 'LinkedToContractNumber', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'LinkedToPremiseNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'LinkedToPremiseName', disabled: true, type: '', required: false, value: '' },
        { name: 'ListedCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'LostBusinessDesc', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'LostBusinessDesc2', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'LostBusinessDesc3', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'LostBusinessRequestNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'MapLatitude', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MapLongitude', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MapPostCode', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MapState', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MapStreetName', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MapStreetNo', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MapStreetType', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MapSuburb', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MatchedContractName', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MatchedContractNumber', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'MatchedPremiseName', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'MatchedPremiseNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'MaterialsCost', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'MaterialsValue', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'menu', disabled: false, type: '', required: false, value: 'Options' },
        { name: 'Monday', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'NationalAccount', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'NationalAccountBranch', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'NationalAccountChecked', disabled: false, type: '', required: false, value: '' },
        { name: 'NegBranchName', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'NegBranchNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'NewContract', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'NextWasteConsignmentNoteNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'NotifyDaysBefore', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'NotifyEmail', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'NotifyEmailDetail', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'NotifyFax', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'NotifyFaxDetail', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'NotifyLine', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'NotifyPhone', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'NotifyPhoneDetail', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'NotifySMS', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'NotifySMSDetail', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'NotifyText', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc1', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc10', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc2', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc3', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc4', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc5', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc6', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc7', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc8', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OccupationDesc9', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'OutsideCityLimits', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'PaymentDesc', disabled: true, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'PaymentTypeCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'PDACloseRecommendationInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'PlanningHighlightInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'PNOL', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'PNOLEffectiveDate', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'PNOLSetUpChargeToApply', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'PNOLSiteRef', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'PNOLSiteRefDesc', disabled: true, type: '', required: false, value: '' },
        { name: 'PNOLUpliftAmount', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'PosEmail', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PosFax', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PosSMS', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PreferredDayOfWeekNote', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PreferredDayOfWeekReasonCode', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'PremiseAddressLine1', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '', maxlength: 40 },
        { name: 'PremiseAddressLine2', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '', maxlength: 40 },
        { name: 'PremiseAddressLine3', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '', maxlength: 40 },
        { name: 'PremiseAddressLine4', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '', maxlength: 40 },
        { name: 'PremiseAddressLine5', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '', maxlength: 40 },
        { name: 'PremiseAliasName', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseAnnualValue', disabled: true, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'PremiseCommenceDate', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'PremiseContactDepartment', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PremiseContactEmail', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PremiseContactFax', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseContactMobile', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseContactName', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PremiseContactPosition', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PremiseContactTelephone', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseDirectoryGridRef', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseDirectoryName', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseDirectoryPage', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'PremiseFixedServiceTime', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'Premise', readonly: true, disabled: false, type: MntConst.eTypeAutoNumber, required: false, value: '', primary: true },
        { name: 'PremiseRowID', readonly: true, disabled: false, type: MntConst.eTypeText, required: false, value: '', primary: true },
        { name: 'PremiseName', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '', maxlength: 40 },
        { name: 'PremiseParkingNote', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PremisePlanningNote', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PremisePostcode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'PremiseReference', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseRegNumber', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseSalesEmployee', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'PremiseServiceNote', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PremiseSpecialInstructions', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'PremiseSRAEmployee', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'PremiseType', disabled: false, type: '', required: false, value: '' },
        { name: 'PremiseVtxGeoCode', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'Priority1', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority10', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority2', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority3', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority4', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority5', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority6', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority7', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority8', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'Priority9', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'ProofOfServEmail', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'ProofOfServFax', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'ProofOfServiceRequired', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'ProofOfServSMS', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'ProofScanRequiredInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'ProofSignatureRequiredInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'PurchaseOrderExpiryDate', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'PurchaseOrderLineNo', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'PurchaseOrderNo', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'RegulatoryAuthorityName', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'RegulatoryAuthorityNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'ReplacementCost', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'ReplacementValue', disabled: false, type: MntConst.eTypeCurrency, required: false, value: '' },
        { name: 'RetainServiceWeekdayInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'RoutingGeonode', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'RoutingScore', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'RowId1', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId10', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId2', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId3', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId4', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId5', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId6', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId7', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId8', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'RowId9', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'SalesEmployeeSurname', disabled: true, type: MntConst.eTypeText, required: false, value: '' }, //?? - Data not populated
        { name: 'Saturday', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'SelPrintRequired', disabled: false, type: '', required: false, value: '' },
        { name: 'selQuickWindowSet1', disabled: false, type: '', required: false, value: '' },
        { name: 'selQuickWindowSet2', disabled: false, type: '', required: false, value: '' },
        { name: 'selQuickWindowSet3', disabled: false, type: '', required: false, value: '' },
        { name: 'selQuickWindowSet4', disabled: false, type: '', required: false, value: '' },
        { name: 'selQuickWindowSet5', disabled: false, type: '', required: false, value: '' },
        { name: 'selQuickWindowSet6', disabled: false, type: '', required: false, value: '' },
        { name: 'selQuickWindowSet7', disabled: false, type: '', required: false, value: '' },
        { name: 'ServiceAdjHrs', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'ServiceAdjMins', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'ServiceReceiptRequired', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'ServiceTimeAdj', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'ShowValueButton', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'SICCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'SICDesc', disabled: true, type: MntConst.eTypeText, required: false, value: '' }, //?? ID not proper
        { name: 'SRAEmployeeSurname', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'Status', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'StoreNumber', disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'StoreType', disabled: false, type: '', required: false, value: '' },
        { name: 'Sunday', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'TechRetentionInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'TechRetentionReasonDesc', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'TelesalesEmployeeCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'TelesalesEmployeeName', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'Thursday', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'TrialPeriodInd', disabled: false, type: '', required: false, value: '' },
        { name: 'Tuesday', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'VehicleTypeDesc', disabled: true, type: '', required: false, value: '' },
        { name: 'VehicleTypeNumber', disabled: false, type: '', required: false, value: '' },
        { name: 'WasteConsignmentNoteExemptInd', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WasteConsignmentNoteExpiryDate', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'WasteRegulatoryPremiseRef', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'Wednesday', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WEDValue', disabled: false, type: MntConst.eTypeDecimal1, required: false, value: '' },
        { name: 'WindowEnd01', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd02', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd03', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd04', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd05', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd06', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd07', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd08', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd09', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd10', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd11', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd12', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd13', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowEnd14', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowPreferredInd01', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WindowPreferredInd02', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WindowPreferredInd03', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WindowPreferredInd04', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WindowPreferredInd05', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WindowPreferredInd06', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WindowPreferredInd07', disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'WindowStart01', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart02', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart03', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart04', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart05', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart06', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart07', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart08', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart09', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart10', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart11', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart12', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart13', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'WindowStart14', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart01', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart02', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart03', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart04', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart05', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart06', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart07', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart08', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart09', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart10', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart11', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart12', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart13', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowStart14', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd01', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd02', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd03', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd04', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd05', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd06', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd07', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd08', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd09', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd10', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd11', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd12', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd13', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'DefaultWindowEnd14', disabled: false, type: MntConst.eTypeTime, required: false, value: '' },
        { name: 'ServiceBranchNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'SalesAreaCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'SalesAreaDesc', disabled: true, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PremiseSRADate', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'PurchaseOrderExpiryDate', disabled: false, type: '', required: false, value: '' },
        { name: 'DateFrom1', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom2', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom3', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom4', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom5', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom6', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom7', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom8', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom9', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateFrom10', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo1', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo2', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo3', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo4', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo5', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo6', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo7', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo8', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo9', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'DateTo10', disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'blankFormControlname', disabled: false, type: '', required: false, value: '' }, //??
        { name: 'SelRoutingSource', disabled: false, type: '', required: false, value: '' },
        { name: 'ClosedTemplateName', disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'CustomerIndicationNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'selCustomerIndicationNumber', disabled: false, type: '', required: false, value: '' },
        { name: 'ServiceNotifyTemplateSMS', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'SelServiceNotifyTemplateSMS', disabled: false, type: '', required: false, value: '' },
        { name: 'ServiceNotifyTemplateEmail', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'SelServiceNotifyTemplateEmail', disabled: false, type: '', required: false, value: '' },
        { name: 'EmployeeLimitChildDrillOptions', disabled: false, type: '', required: false, value: '' },
        { name: 'DiscountCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'LanguageCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'ClosedCalendarTemplateNumber', disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'PNOLiCABSLevel', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'PNOLDescription', disabled: true, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'TechRetentionReasonCode', disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'ForceRefresh', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'ContractHasExpired', readonly: true, disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'RunningReadOnly', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'origPNOL', readonly: true, disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'origPNOLiCABSLevel', readonly: true, disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'origPNOLSiteRef', readonly: true, disabled: false, type: MntConst.eTypeCode, required: false, value: '' },
        { name: 'origPNOLEffectiveDate', readonly: true, disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'PNOLEffectiveDefault', readonly: true, disabled: false, type: MntConst.eTypeDate, required: false, value: '' },
        { name: 'CallLogID', readonly: true, disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'CurrentCallLogID', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'WindowClosingName', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'ClosedWithChanges', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'SelectedSRA', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'SelectedTrigger', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'SelectedRCM', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'ProspectNumber', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'RoutingSource', readonly: true, disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'AddressError', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'NewPremiseRowID', readonly: true, disabled: false, type: MntConst.eTypeText, required: false, value: '' },
        { name: 'PrintRequired', readonly: true, disabled: false, type: MntConst.eTypeInteger, required: false, value: '' },
        { name: 'TelesalesInd', readonly: true, disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '' },
        { name: 'GridUniqueID', readonly: true, disabled: false, type: MntConst.eTypeTextFree, required: false, value: '' },
        { name: 'RCMNumber', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'OriPremiseVtxGeoCode', readonly: true, disabled: false, type: '', required: false, value: '' },
        { name: 'save', readonly: false, disabled: false, type: '', required: false, value: 'Save', primary: true }, //Save
        { name: 'cancel', readonly: false, disabled: false, type: '', required: false, value: 'Cancel', primary: true }, //Cancel
        { name: 'BtnAmendContact', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Contact Details
        { name: 'cmdGetAddress', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Get Address
        { name: 'cmdGeocode', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Geocode
        { name: 'cmdVtxGeoCode', readonly: false, disabled: false, required: false, primary: false, value: '' }, //GetGeoCode
        { name: 'cmdValue', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Future Change
        { name: 'cmdGetLatAndLong', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Resolve Address
        { name: 'cmdMatchPremise', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Match Premise
        { name: 'cmdResendPremises', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Resend Premises
        { name: 'cmdViewLinkedPremises', readonly: false, disabled: false, required: false, primary: false, value: '' }, //View Linked Premises
        { name: 'cmdViewAssociatedPremises', readonly: false, disabled: false, required: false, primary: false, value: '' }, //View Associated Premises
        { name: 'cmdAddNextHazard', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Add Next Hazard
        { name: 'cmdQuestionnaireComp', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Questionnaire Complete
        { name: 'cmdCopyPremise', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Copy
        { name: 'cmdSRAGenerateText', readonly: false, disabled: false, required: false, primary: false, value: '' }, //Generate Text
        { name: 'tdCustomerInfo', readonly: false, disabled: false, required: false, primary: false, value: '' } //Customer Information
    ];

    public uiDisplay = {
        tdCustomerInfo: false,
        tdPremiseAnnualValueLab: false, //not in html
        tdPremiseAnnualValue: false, //not in html
        tdNationalAccount: false,
        tdDrivingChargeValueLab: false,
        tdDrivingChargeValue: false, //not in html

        labelDiscountCode: true, //anomaly
        labelInactiveEffectDate: true,

        DiscountCode: true,
        DiscountDesc: true, //html error
        LostBusinessDesc: false,
        InactiveEffectDate: true,
        AnyPendingBelow: true,
        grdPremiseMaintenanceControl: true, //not in html
        cmdGetAddress: true,
        cmdValue: true,
        cmdGetLatAndLong: false,

        expired: false,
        nationalAccount: false,
        badDebtAccountCheckbox: false,
        badDebtAccount: false,
        pnol: false,
        trialPeriodInd: false,

        //PremiseMaintenance
        tdWEDLabel: false,
        WEDValue: false,
        tdPremiseFixedServiceTime: false,
        tdPremiseFixedServiceTime1: false,
        trPNOL: false,
        trPNOLiCABSLevel: false,
        tdDrivingChargeIndLab: false,
        tdDrivingChargeInd: false,
        trBarcodeRequired: false,
        trSignatureRequired: false,
        trPurchaseOrderDetails: false,
        trSICCode: false,
        trVehicleTypeNumber: false,
        cmdGeocode: false,
        tdGeonode: false,
        tdGPSScore: false,
        trEnableLinkedPremises: false,
        trEnableAssociatedPremises: false,
        tdspanContractPostCode: false,
        tdContractPostCode: false,
        trRegulatoryAuthorityNumber: false,
        trMatchContract: false,
        trMatchPremise: false,
        trVtxGeoCode: false,
        tdOutsideCityLimits: false,
        tdOutsideCityLimitslab: false,
        thControl: false,
        grdGuarantee: false,
        grCustomerInt: false,
        trCreateNewSRA: false,
        trComment2: false,
        trAdditionalComment2: false,
        tdPurchaseOrderExpiryDate: false,
        tdBtnAmendContact: false,
        tdPNOL: false,
        tdHyperSens: false,
        tdEnvironmentalRestrictedAreaInd: false,
        cmdMatchPremise: false,
        tdContractHasExpired: false,
        trBatchProcessInformation: false,
        trAddToPNOLUpliftAmount: false,
        trAddToPNOLSetupChargeToApply: false,
        tdbtnAmendContact: false,
        grdTimeWindows: false,

        render: {
            BatchProcessInformation: ''
        }
    };

    //Dropdown
    public dropDown = {
        menu: [],
        CustomerIndicationNumber: [],
        ServiceBranchNumber: [],
        DiscountCode: [],
        LanguageCode: [],

        CustomerAvailTemplate: [],
        ClosedCalendarTemplate: [],
        PreferredDayOfWeekReasonLang: [],
        SICCodeLang: [],
        PestNetOnLineLevel: [],
        PremiseTechRetentionReasonsLang: [],
        NotificationTemplate: []
    };

    public ellipsis = {
        contractNumberEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            showAddNew: false,
            childparams: {
                'parentMode': 'LookUp',
                'currentContractType': '',
                'initEmpty': false,
                'accountNumber': '',
                'accountName': '',
                'enableAccountSearch': false
            },

            component: ContractSearchComponent
        },
        premiseNumberEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'Search',
                'currentContractType': '',
                'ContractNumber': '',
                'ContractName': '',
                'AccountNumber': '',
                'PremisePostcode': '',
                'PremiseAddressLine1': '',
                'PremiseAddressLine2': '',
                'PremiseAddressLine3': '',
                'PremiseAddressLine4': '',
                'PremiseAddressLine5': '',
                'showAddNew': true
            },
            component: PremiseSearchComponent
        },
        linkedContractNumberEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            showAddNew: false,
            childparams: {
                'parentMode': 'LookUp',
                'currentContractType': '',
                'initEmpty': false
            },
            component: ContractSearchComponent
        },
        linkedPremiseNumberEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'Search',
                'currentContractType': '',
                'ContractNumber': '',
                'ContractName': '',
                'AccountNumber': '',
                'showAddNew': false
            },
            component: PremiseSearchComponent
        },
        customerTypeEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp-Premise',
                'currentContractType': ''
            },
            component: CustomerTypeSearchComponent
        },
        sicCodeEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp-Premise',
                'currentContractType': ''
            },
            component: SICSearchComponent
        },
        telesalesEmployeeEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp-Telesales',
                'currentContractType': ''
            },
            component: EmployeeSearchComponent
        },
        vehicleTypeEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp',
                'currentContractType': ''
            },
            component: ScreenNotReadyComponent //TODO - Business/iCABSBVehicleTypeSearch.htm
        },
        siteReferenceEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp',
                'isEllipsis': true,
                'AccountNumber': '',
                'ContractNumber': '',
                'ContractName': '',
                'SearchPostcode': '',
                'PremiseName': '',
                'PremiseAddressLine1': '',
                'PremiseAddressLine2': '',
                'PremiseAddressLine3': '',
                'PremiseAddressLine4': '',
                'PremiseAddressLine5': '',
                'PremisePostcode': ''
            },
            modalConfig: {
                backdrop: 'static',
                keyboard: true
            },
            component: PNOLPremiseSearchGridComponent
        },
        invoiceGrpNumberEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'PremiseMaintenanceSearch',
                'isEllipsis': true,
                'AccountNumber': '',
                'AccountName': '',
                'ContractNumber': '',
                'PremiseNumber': ''
            },
            // component: InvoiceGroupSearchComponent
            component: InvoiceGroupGridComponent
        },
        employeeSearchComponent: {
            disabled: true,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp'
            },
            component: ScreenNotReadyComponent //TODO Application/iCABSARPrefTechSearch.htm -- Param=1,2,3 etc
        },
        employeeSearchEllipsis: {
            disabled: true,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp-PremiseSRAEmployee'
            },
            component: EmployeeSearchComponent
        },
        SalesAreaSearchComponent: {
            disabled: true,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp-Premise',
                'ServiceBranchNumber': ''
            },
            component: SalesAreaSearchComponent
        },
        MPAFSearch: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            hide: true,
            childparams: {
                parentMode: 'Premise',
                PostCode: '',
                State: '',
                Town: '',
                BranchNumber: ''
            },
            component: ScreenNotReadyComponent //TODO iCABSMPAFSearch.html
        },
        MarktSelectSearch: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            hide: true,
            childparams: {
                parentMode: 'Premise',
                PremiseName: '',
                PremiseAddressLine1: '',
                PremiseAddressLine2: '',
                PremiseAddressLine3: '',
                PremiseAddressLine4: '',
                countryCode: '',
                PremisePostcode: '',
                PremiseContactTelephone: '',
                PremiseContactFax: '',
                PremiseReference: '',
                PremiseRegNumber: '',
                CustomerTypeCode: ''
            },
            component: MarktSelectSearchComponent
        },
        PostCodeSearch: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            hide: true,
            childparams: {
                parentMode: 'Premise',
                PremisePostCode: '',
                PremiseAddressLine5: '',
                PremiseAddressLine4: '',
                BranchNumber: ''
            },
            component: PostCodeSearchComponent
        },
        AUPostCodeSearch: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            hide: true,
            childparams: {
                parentMode: 'Premise',
                town: '',
                state: '',
                postCode: ''
            },
            component: AUPostcodeSearchComponent
        },
        PestNetOnLineLevelSearch: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            hide: false,
            childparams: {
                parentMode: 'LookUp'
            },
            component: PestNetOnLineLevelSearchComponent
        },
        RegulatoryAuthorityEllipsis: {
            disabled: false,
            showCloseButton: true,
            showHeader: true,
            childparams: {
                'parentMode': 'LookUp-Premise'
            },
            component: ScreenNotReadyComponent //RegulatoryAuthoritySearchComponent
        }
    };

    //TABS
    public tab_iCABSAPremiseMaintenanceAddrRes = {
        tab1: { id: 'grdAddress', name: 'Address', visible: false, active: true },
        tab2: { id: 'grdGeneral', name: 'General', visible: false, active: false },
        tab3: { id: 'grdSiteRiskAssessment', name: 'Site Risk Assessment', visible: false, active: false },
        tab4: { id: 'grdNotificationMethods', name: 'Notification Methods', visible: false, active: false },
        tab5: { id: 'grdDayRestrictions', name: 'Day Restrictions', visible: false, active: false },
        tab6: { id: 'grdTechs', name: 'Techs', visible: false, active: false },
        tab7: { id: 'grdDataRestrictions', name: 'Data Restrictions', visible: false, active: false },
        tab8: { id: 'grdAccessTimes', name: 'Access Times', visible: false, active: false },
        tab9: { id: 'grdInvoiceNarrative', name: 'Invoice Narrative', visible: false, active: false }
    };
    public tab_iCABSAPremiseMaintenance = {
        tab1: { id: 'grdPremiseAddress', name: 'Address', visible: false, active: true },
        tab2: { id: 'grdPremiseGeneral', name: 'General', visible: false, active: false },
        tab3: { id: 'grdPNOL', name: 'PestNetOnline', visible: false, active: false },
        tab4: { id: 'grdGblSRAInput', name: 'Global SRA Input', visible: false, active: false },
        tab5: { id: 'grdGblSRAEdit', name: 'Global SRA Edit', visible: false, active: false },
        tab6: { id: 'grdSpecial', name: 'Site Risk Assessment', visible: false, active: false },
        tab7: { id: 'grdAddComments', name: 'Additional Comments', visible: false, active: false },
        tab8: { id: 'grdTimeWindows', name: 'Planning', visible: false, active: false },
        tab9: { id: 'grdPremiseWaste', name: 'PremiseWaste', visible: false, active: false },
        tab10: { id: 'grdDisplayValue1', name: 'DisplayValue1', visible: false, active: false },
        tab11: { id: 'grdGuarantee', name: 'Guarantee', visible: false, active: false },
        tab12: { id: 'grdCustomerInt', name: 'Customer Integration', visible: false, active: false },
        tab13: { id: 'grdPremiseInvoiceNarrative', name: 'Invoice Narrative', visible: false, active: false },
        tab14: { id: 'grdPremiseServiceNote', name: 'Servicing', visible: false, active: false }
    };

    public viewChild = {};
}
