import { MarktSelectSearchComponent } from './../../internal/search/iCABSMarktSelectSearch.component';
import { PostCodeSearchComponent } from './../../internal/search/iCABSBPostcodeSearch.component';
import { PNOLPremiseSearchGridComponent } from './../../internal/grid-search/iCABSAPNOLPremiseSearchGrid.component';
import { ScreenNotReadyComponent } from './../../../shared/components/screenNotReady';
import { CustomerTypeSearchComponent } from './../../internal/search/iCABSSCustomerTypeSearch';
import { InvoiceGroupGridComponent } from './../../internal/grid-search/iCABSAInvoiceGroupGrid';
import { SalesAreaSearchComponent } from './../../internal/search/iCABSBSalesAreaSearch.component';
import { PremiseSearchComponent } from './../../internal/search/iCABSAPremiseSearch';
import { ContractSearchComponent } from './../../internal/search/iCABSAContractSearch';
import { EmployeeSearchComponent } from '../../../app/internal/search/iCABSBEmployeeSearch';
import { MntConst } from '../../../shared/services/riMaintenancehelper';
export var UiControls = (function () {
    function UiControls() {
        this.controls = [
            { name: 'ContractNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: true },
            { name: 'PremiseNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: true },
            { name: 'ContractTypeCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: true },
            { name: 'AccessFrom1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom10', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom8', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessFrom9', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo10', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo8', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccessTo9', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AccountName', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'AccountNumber', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'AdditionalActionComments', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AdditionalComments1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AdditionalComments2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AdditionalLocations', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks10', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks8', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AllowAllTasks9', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AnyPendingBelow', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'AppointmentDetailDesc', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AppointmentRequiredInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'AssociatedToPremiseNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'BadDebtAccount', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CICFWOReq', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CICFWOSep', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CICResponseSLA', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CICustRefReq', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CIFirstSLAEscDays', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CIRWOReq', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CISubSLAEscDays', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ClientReference', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ContractName', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'CreateNewInvoiceGroupInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CreateNewSRA', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CustomerAvailTemplateDesc', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CustomerAvailTemplateID', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CustomerInfoAvailable', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CustomerTypeCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CustomerTypeDesc', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'DisableList', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DisplayQty', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DrivingChargeInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DrivingChargeValue', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode10', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode8', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeCode9', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname1', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname10', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname2', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname3', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname4', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname5', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname6', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname7', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname8', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeSurname9', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'EnvironmentalRestrictedAreaInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EnvironmentalRestrictedAreaText', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ErrorMessageDesc', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Friday', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'GblSRAAdditionalSRA', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'GblSRAAdditionalSRADocReftext', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'GblSRADesc', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'GblSRATypeCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'GPSCoordinateX', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'GPSCoordinateY', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'GuaranteeNumberBedrooms', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'HyperSensitive', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'InactiveEffectDate', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'InitialTreatmentInstructions', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'InvoiceGroupDesc', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'InvoiceGroupNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'InvoiceNarrativeText', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'InvoiceSuspendInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'InvoiceSuspendText', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'LabourCost', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'LabourValue', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'LinkedToContractName', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'LinkedToContractNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'LinkedToPremiseNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'LinkedToPremiseName', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'ListedCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'LostBusinessDesc', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'LostBusinessDesc2', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'LostBusinessDesc3', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'LostBusinessRequestNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MapLatitude', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MapLongitude', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MapPostCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MapState', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MapStreetName', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MapStreetNo', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MapStreetType', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MapSuburb', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MatchedContractName', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'MatchedContractNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MatchedPremiseName', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'MatchedPremiseNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MaterialsCost', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'MaterialsValue', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'menu', readonly: false, disabled: false, type: '', required: false, value: 'Options', primary: false },
            { name: 'Monday', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NationalAccount', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NationalAccountBranch', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NationalAccountChecked', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NegBranchName', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NegBranchNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NewContract', readonly: false, disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '', primary: false },
            { name: 'NextWasteConsignmentNoteNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyDaysBefore', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyEmail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyEmailDetail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyFax', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyFaxDetail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyLine', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyPhone', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyPhoneDetail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifySMS', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifySMSDetail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'NotifyText', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc1', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc10', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc2', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc3', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc4', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc5', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc6', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc7', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc8', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OccupationDesc9', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'OutsideCityLimits', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PaymentDesc', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'PaymentTypeCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PDACloseRecommendationInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PlanningHighlightInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PNOL', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PNOLEffectiveDate', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PNOLSetUpChargeToApply', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PNOLSiteRef', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PNOLSiteRefDesc', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'PNOLUpliftAmount', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PosEmail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PosFax', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PosSMS', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PreferredDayOfWeekNote', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PreferredDayOfWeekReasonCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseAddressLine1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false, maxlength: 40 },
            { name: 'PremiseAddressLine2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false, maxlength: 40 },
            { name: 'PremiseAddressLine3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false, maxlength: 40 },
            { name: 'PremiseAddressLine4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false, maxlength: 40 },
            { name: 'PremiseAddressLine5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false, maxlength: 40 },
            { name: 'PremiseAliasName', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseAnnualValue', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'PremiseCommenceDate', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseContactDepartment', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseContactEmail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseContactFax', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseContactMobile', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseContactName', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseContactPosition', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseContactTelephone', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseDirectoryGridRef', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseDirectoryName', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseDirectoryPage', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseFixedServiceTime', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Premise', readonly: true, disabled: false, type: '', required: false, value: '', primary: true },
            { name: 'PremiseRowID', readonly: true, disabled: false, type: '', required: false, value: '', primary: true },
            { name: 'PremiseName', readonly: false, disabled: false, type: '', required: false, value: '', primary: false, maxlength: 40 },
            { name: 'PremiseParkingNote', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremisePlanningNote', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremisePostcode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseReference', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseRegNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseSalesEmployee', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseServiceNote', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseSpecialInstructions', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseSRADate', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseSRAEmployee', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseType', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PremiseVtxGeoCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority10', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority8', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Priority9', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ProofOfServEmail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ProofOfServFax', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ProofOfServiceRequired', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ProofOfServSMS', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ProofScanRequiredInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ProofSignatureRequiredInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PurchaseOrderExpiryDate', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PurchaseOrderLineNo', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PurchaseOrderNo', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RegulatoryAuthorityName', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'RegulatoryAuthorityNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ReplacementCost', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ReplacementValue', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RetainServiceWeekdayInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RoutingGeonode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RoutingScore', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId10', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId8', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'RowId9', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'SalesEmployeeSurname', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'Saturday', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'SelPrintRequired', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'selQuickWindowSet1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'selQuickWindowSet2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'selQuickWindowSet3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'selQuickWindowSet4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'selQuickWindowSet5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'selQuickWindowSet6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'selQuickWindowSet7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ServiceAdjHrs', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ServiceAdjMins', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ServiceReceiptRequired', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ServiceTimeAdj', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ShowValueButton', readonly: false, disabled: false, type: MntConst.eTypeCheckBox, required: false, value: '', primary: false },
            { name: 'SICCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'SICDesc', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'SRAEmployeeSurname', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'Status', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'StoreNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'StoreType', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Sunday', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'TechRetentionInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'TechRetentionReasonDesc', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'TelesalesEmployeeCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'TelesalesEmployeeName', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'Thursday', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'TrialPeriodInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Tuesday', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'VehicleTypeDesc', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'VehicleTypeNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WasteConsignmentNoteExemptInd', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WasteConsignmentNoteExpiryDate', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WasteRegulatoryPremiseRef', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'Wednesday', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WEDValue', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WindowEnd01', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd02', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd03', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd04', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd05', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd06', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd07', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd08', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd09', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd10', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd11', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd12', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd13', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowEnd14', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowPreferredInd01', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WindowPreferredInd02', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WindowPreferredInd03', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WindowPreferredInd04', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WindowPreferredInd05', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WindowPreferredInd06', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WindowPreferredInd07', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'WindowStart01', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart02', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart03', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart04', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart05', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart06', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart07', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart08', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart09', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart10', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart11', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart12', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart13', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'WindowStart14', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart01', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart02', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart03', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart04', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart05', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart06', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart07', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart08', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart09', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart10', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart11', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart12', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart13', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowStart14', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd01', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd02', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd03', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd04', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd05', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd06', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd07', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd08', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd09', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd10', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd11', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd12', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd13', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'DefaultWindowEnd14', readonly: false, disabled: false, type: MntConst.eTypeTime, required: false, value: '', primary: false },
            { name: 'ServiceBranchNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'SalesAreaCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'SalesAreaDesc', readonly: false, disabled: true, type: '', required: false, value: '', primary: false },
            { name: 'PremiseSRADate', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PurchaseOrderExpiryDate', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom8', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom9', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateFrom10', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo1', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo2', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo3', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo4', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo5', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo6', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo7', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo8', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo9', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DateTo10', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'blankFormControlname', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'SelRoutingSource', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ClosedTemplateName', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'CustomerIndicationNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'selCustomerIndicationNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ServiceNotifyTemplateSMS', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'SelServiceNotifyTemplateSMS', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ServiceNotifyTemplateEmail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'SelServiceNotifyTemplateEmail', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'EmployeeLimitChildDrillOptions', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'DiscountCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'LanguageCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ClosedCalendarTemplateNumber', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'PNOLiCABSLevel', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'TechRetentionReasonCode', readonly: false, disabled: false, type: '', required: false, value: '', primary: false },
            { name: 'ForceRefresh', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'ContractHasExpired', type: MntConst.eTypeCheckBox, readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'RunningReadOnly', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'origPNOL', readonly: true, type: MntConst.eTypeCheckBox, disabled: false, required: false, primary: false, value: '' },
            { name: 'origPNOLiCABSLevel', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'origPNOLSiteRef', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'origPNOLEffectiveDate', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'PNOLEffectiveDefault', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'CallLogID', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'CurrentCallLogID', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'WindowClosingName', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'ClosedWithChanges', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'SelectedSRA', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'SelectedTrigger', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'SelectedRCM', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'ProspectNumber', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'RoutingSource', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'AddressError', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'NewPremiseRowID', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'PrintRequired', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'TelesalesInd', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'GridUniqueID', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'RCMNumber', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'OriPremiseVtxGeoCode', readonly: true, disabled: false, required: false, primary: false, value: '' },
            { name: 'save', readonly: false, disabled: false, type: '', required: false, value: 'Save', primary: true },
            { name: 'cancel', readonly: false, disabled: false, type: '', required: false, value: 'Cancel', primary: true },
            { name: 'BtnAmendContact', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdGetAddress', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdGeocode', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdVtxGeoCode', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdValue', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdGetLatAndLong', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdMatchPremise', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdResendPremises', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdViewLinkedPremises', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdViewAssociatedPremises', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdAddNextHazard', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdQuestionnaireComp', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'cmdCopyPremise', readonly: false, disabled: false, required: false, primary: false, value: '' },
            { name: 'tdCustomerInfo', readonly: false, disabled: false, required: false, primary: false, value: '' }
        ];
        this.uiDisplay = {
            tdCustomerInfo: false,
            tdPremiseAnnualValueLab: false,
            tdPremiseAnnualValue: false,
            tdNationalAccount: false,
            tdDrivingChargeValueLab: false,
            tdDrivingChargeValue: false,
            labelDiscountCode: true,
            labelInactiveEffectDate: true,
            DiscountCode: true,
            DiscountDesc: true,
            LostBusinessDesc: false,
            InactiveEffectDate: true,
            AnyPendingBelow: true,
            grdPremiseMaintenanceControl: true,
            cmdGetAddress: true,
            cmdValue: true,
            cmdGetLatAndLong: false,
            expired: false,
            nationalAccount: false,
            badDebtAccountCheckbox: false,
            badDebtAccount: false,
            pnol: false,
            trialPeriodInd: false,
            tdWEDLabel: false,
            WEDValue: false,
            tdPremiseFixedServiceTime: false,
            tdPremiseFixedServiceTime1: false,
            trPNOL: false,
            trPNOLiCABSLevel: false,
            tdDrivingChargeIndLab: false,
            tdDrivingChargeInd: false,
            trBarcodeRequired: false,
            trSignatureRequired: false,
            trPurchaseOrderDetails: false,
            trSICCode: false,
            trVehicleTypeNumber: false,
            cmdGeocode: false,
            tdGeonode: false,
            tdGPSScore: false,
            trEnableLinkedPremises: false,
            trEnableAssociatedPremises: false,
            tdspanContractPostCode: false,
            tdContractPostCode: false,
            trRegulatoryAuthorityNumber: false,
            trMatchContract: false,
            trMatchPremise: false,
            trVtxGeoCode: false,
            tdOutsideCityLimits: false,
            tdOutsideCityLimitslab: false,
            thControl: false,
            grdGuarantee: false,
            grCustomerInt: false,
            trCreateNewSRA: false,
            trComment2: false,
            trAdditionalComment2: false,
            tdPurchaseOrderExpiryDate: false,
            tdBtnAmendContact: false,
            tdPNOL: false,
            tdHyperSens: false,
            tdEnvironmentalRestrictedAreaInd: false,
            cmdMatchPremise: false,
            tdContractHasExpired: false,
            trBatchProcessInformation: false,
            trAddToPNOLUpliftAmount: false,
            trAddToPNOLSetupChargeToApply: false,
            tdbtnAmendContact: false,
            grdTimeWindows: false,
            render: {
                BatchProcessInformation: ''
            }
        };
        this.dropDown = {
            menu: [],
            CustomerIndicationNumber: [],
            ServiceBranchNumber: [],
            DiscountCode: [],
            LanguageCode: [],
            CustomerAvailTemplate: [],
            ClosedCalendarTemplate: [],
            PreferredDayOfWeekReasonLang: [],
            SICCodeLang: [],
            PestNetOnLineLevel: [],
            PremiseTechRetentionReasonsLang: [],
            NotificationTemplate: []
        };
        this.ellipsis = {
            contractNumberEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                showAddNew: false,
                childparams: {
                    'parentMode': 'LookUp',
                    'currentContractType': '',
                    'initEmpty': false
                },
                component: ContractSearchComponent
            },
            premiseNumberEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'Search',
                    'currentContractType': '',
                    'ContractNumber': '',
                    'ContractName': '',
                    'AccountNumber': '',
                    'showAddNew': true
                },
                component: PremiseSearchComponent
            },
            linkedContractNumberEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                showAddNew: false,
                childparams: {
                    'parentMode': 'LookUp',
                    'currentContractType': '',
                    'initEmpty': false
                },
                component: ContractSearchComponent
            },
            linkedPremiseNumberEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'Search',
                    'currentContractType': '',
                    'ContractNumber': '',
                    'ContractName': '',
                    'AccountNumber': '',
                    'showAddNew': false
                },
                component: PremiseSearchComponent
            },
            customerTypeEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'Search',
                    'currentContractType': ''
                },
                component: CustomerTypeSearchComponent
            },
            sicCodeEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'LookUp-Premise',
                    'currentContractType': ''
                },
                component: ScreenNotReadyComponent
            },
            telesalesEmployeeEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'LookUp-Telesales',
                    'currentContractType': ''
                },
                component: EmployeeSearchComponent
            },
            vehicleTypeEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'LookUp',
                    'currentContractType': ''
                },
                component: ScreenNotReadyComponent
            },
            siteReferenceEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'LookUp',
                    'isEllipsis': true,
                    'AccountNumber': '',
                    'ContractNumber': '',
                    'ContractName': '',
                    'SearchPostcode': '',
                    'PremiseName': '',
                    'PremiseAddressLine1': '',
                    'PremiseAddressLine2': '',
                    'PremiseAddressLine3': '',
                    'PremiseAddressLine4': '',
                    'PremiseAddressLine5': '',
                    'PremisePostcode': ''
                },
                modalConfig: {
                    backdrop: 'static',
                    keyboard: true
                },
                component: PNOLPremiseSearchGridComponent
            },
            invoiceGrpNumberEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'PremiseMaintenanceSearch',
                    'isEllipsis': true,
                    'AccountNumber': '',
                    'AccountName': '',
                    'ContractNumber': '',
                    'PremiseNumber': ''
                },
                component: InvoiceGroupGridComponent
            },
            employeeSearchComponent: {
                disabled: true,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'LookUp'
                },
                component: ScreenNotReadyComponent
            },
            SalesAreaSearchComponent: {
                disabled: true,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'LookUp-Premise',
                    'ServiceBranchNumber': ''
                },
                component: SalesAreaSearchComponent
            },
            MPAFSearch: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                hide: true,
                childparams: {
                    parentMode: 'Premise',
                    PostCode: '',
                    State: '',
                    Town: '',
                    BranchNumber: ''
                },
                component: ScreenNotReadyComponent
            },
            MarktSelectSearch: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                hide: true,
                childparams: {
                    parentMode: 'Premise',
                    PremiseAddressLine1: '',
                    PremiseAddressLine2: '',
                    PremiseAddressLine4: '',
                    PremisePostcode: ''
                },
                component: MarktSelectSearchComponent
            },
            PostCodeSearch: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                hide: true,
                childparams: {
                    parentMode: 'Premise',
                    PremisePostCode: '',
                    PremiseAddressLine5: '',
                    PremiseAddressLine4: '',
                    BranchNumber: ''
                },
                component: PostCodeSearchComponent
            },
            RegulatoryAuthorityEllipsis: {
                disabled: false,
                showCloseButton: true,
                showHeader: true,
                childparams: {
                    'parentMode': 'LookUp-Premise'
                },
                component: ScreenNotReadyComponent
            }
        };
        this.tab_iCABSAPremiseMaintenanceAddrRes = {
            tab1: { id: 'grdAddress', name: 'Address', visible: false, active: true },
            tab2: { id: 'grdGeneral', name: 'General', visible: false, active: false },
            tab3: { id: 'grdSiteRiskAssessment', name: 'Site Risk Assessment', visible: false, active: false },
            tab4: { id: 'grdNotificationMethods', name: 'Notification Methods', visible: false, active: false },
            tab5: { id: 'grdDayRestrictions', name: 'Day Restrictions', visible: false, active: false },
            tab6: { id: 'grdTechs', name: 'Techs', visible: false, active: false },
            tab7: { id: 'grdDataRestrictions', name: 'Data Restrictions', visible: false, active: false },
            tab8: { id: 'grdAccessTimes', name: 'Access Times', visible: false, active: false },
            tab9: { id: 'grdInvoiceNarrative', name: 'Invoice Narrative', visible: false, active: false }
        };
        this.tab_iCABSAPremiseMaintenance = {
            tab1: { id: 'grdPremiseAddress', name: 'Address', visible: false, active: true },
            tab2: { id: 'grdPremiseGeneral', name: 'General', visible: false, active: false },
            tab3: { id: 'grdPNOL', name: 'PestNetOnline', visible: false, active: false },
            tab4: { id: 'grdGblSRAInput', name: 'Global SRA Input', visible: false, active: false },
            tab5: { id: 'grdGblSRAEdit', name: 'Global SRA Edit', visible: false, active: false },
            tab6: { id: 'grdSpecial', name: 'Site Risk Assessment', visible: false, active: false },
            tab7: { id: 'grdAddComments', name: 'Additional Comments', visible: false, active: false },
            tab8: { id: 'grdTimeWindows', name: 'Planning', visible: false, active: false },
            tab9: { id: 'grdPremiseWaste', name: 'PremiseWaste', visible: false, active: false },
            tab10: { id: 'grdDisplayValue1', name: 'DisplayValue1', visible: false, active: false },
            tab11: { id: 'grdGuarantee', name: 'Guarantee', visible: false, active: false },
            tab12: { id: 'grdCustomerInt', name: 'Customer Integration', visible: false, active: false },
            tab13: { id: 'grdPremiseInvoiceNarrative', name: 'Invoice Narrative', visible: false, active: false },
            tab14: { id: 'grdPremiseServiceNote', name: 'Servicing', visible: false, active: false }
        };
        this.viewChild = {};
    }
    return UiControls;
}());
