import { BaseComponent } from './../../../../app/base/BaseComponent';
import { PageIdentifier } from './../../../../app/base/PageIdentifier';
import { Component, OnInit,Injector } from '@angular/core';
@Component({
    templateUrl: 'iCABSSBusinessMaintenance.html'
})

export class BusinessMaintenanceComponent extends BaseComponent implements OnInit {
    public pageId: string = '';
    public controls = [
        { name: 'BusinessCode'},
        { name: 'LastAPIMonth'},
        { name: 'LastAPIYear'},
        { name: 'APILessThanValue'},
        { name: 'menu'},
        { name: 'NextAccountNumber'},
        { name: 'NextContractJobNumber'},
        { name: 'SalesTradingYear'},
        { name: 'SalesTradingMonth'},
        { name: 'TurnoverTradingYear'},
        { name: 'TurnoverTradingMonth'},
        { name: 'ValidateLowerValue'},
        { name: 'ValidateUpperValue'},
        { name: 'ForwardDateMaxMonths'},
        { name: 'BackDateMaxMonths'},
        { name: 'CreditWarningValue'},
        { name: 'MinimumInvoiceLevyValue'},
        { name: 'MinimumInvoiceNumber'},
        { name: 'ReferenceNumber1'},
        { name: 'ReferenceNumber2'},
        { name: 'ReferenceNumber3'},
        { name: 'ReferenceNumber4'},
        { name: 'OACompanyNumber'},
        { name: 'OATurnoverDocumentID'},
        { name: 'OAInvoiceDocumentID'},
        { name: 'OASLControlAccount'},
        { name: 'OAVATAccount'},
        { name: 'OAUCPAccount'},
        { name: 'CostCentre'},
        { name: 'InSightID'},
        { name: 'InSightLink'},
        { name: 'FromEmailAddress'},
        { name: 'WasteRegulatoryCarrierName'},
        { name: 'WasteRegulatoryRegistrationNum'},
        { name: 'DefaultWindowStart01'},
        { name: 'DefaultWindowEnd01'},
        { name: 'DefaultWindowStart02'},
        { name: 'DefaultWindowEnd02'},
        { name: 'DefaultWindowStart03'},
        { name: 'DefaultWindowEnd03'},
        { name: 'DefaultWindowStart04'},
        { name: 'DefaultWindowEnd04'},
        { name: 'DefaultWindowStart05'},
        { name: 'DefaultWindowEnd05'},
        { name: 'DefaultWindowStart06'},
        { name: 'DefaultWindowEnd06'},
        { name: 'DefaultWindowStart07'},
        { name: 'DefaultWindowEnd07'},
        { name: 'DefaultWindowStart08'},
        { name: 'DefaultWindowEnd08'},
        { name: 'DefaultWindowStart09'},
        { name: 'DefaultWindowEnd09'},
        { name: 'DefaultWindowStart10'},
        { name: 'DefaultWindowEnd10'},
        { name: 'DefaultWindowStart11'},
        { name: 'DefaultWindowEnd11'},
        { name: 'DefaultWindowStart12'},
        { name: 'DefaultWindowEnd12'},
        { name: 'DefaultWindowStart13'},
        { name: 'DefaultWindowEnd13'},
        { name: 'DefaultWindowStart14'},
        { name: 'DefaultWindowEnd14'},
        { name: 'OAEMail'},
        { name: '1WindowStart01'},
        { name: '1WindowEnd01'},
        { name: '1WindowDayInd01'},
        { name: '2WindowStart01'},
        { name: '2WindowEnd01'},
        { name: '2WindowDayInd01'},
        { name: '3WindowStart01'},
        { name: '3WindowEnd01'},
        { name: '3WindowDayInd01'},
        { name: '1WindowStart02'},
        { name: '1WindowEnd02'},
        { name: '1WindowDayInd02'},
        { name: '2WindowStart02'},
        { name: '2WindowEnd02'},
        { name: '2WindowDayInd02'},
        { name: '3WindowStart02'},
        { name: '3WindowEnd02'},
        { name: '3WindowDayInd02'},
        { name: '1WindowStart03'},
        { name: '1WindowEnd03'},
        { name: '1WindowDayInd03'},
        { name: '2WindowStart03'},
        { name: '2WindowEnd03'},
        { name: '2WindowDayInd03'},
        { name: '3WindowStart03'},
        { name: '3WindowEnd03'},
        { name: '3WindowDayInd03'},
        { name: '1WindowStart04'},
        { name: '1WindowEnd04'},
        { name: '1WindowDayInd04'},
        { name: '2WindowStart04'},
        { name: '2WindowEnd04'},
        { name: '2WindowDayInd04'},
        { name: '3WindowStart04'},
        { name: '3WindowEnd04'},
        { name: '3WindowDayInd04'},
        { name: '1WindowStart05'},
        { name: '1WindowEnd05'},
        { name: '1WindowDayInd05'},
        { name: '2WindowStart05'},
        { name: '2WindowEnd05'},
        { name: '2WindowDayInd05'},
        { name: '3WindowStart05'},
        { name: '3WindowEnd05'},
        { name: '3WindowDayInd05'},
        { name: '1WindowStart06'},
        { name: '1WindowEnd06'},
        { name: '1WindowDayInd06'},
        { name: '2WindowStart06'},
        { name: '2WindowEnd06'},
        { name: '2WindowDayInd06'},
        { name: '3WindowStart06'},
        { name: '3WindowEnd06'},
        { name: '3WindowDayInd06'},
        { name: '1WindowStart07'},
        { name: '1WindowEnd07'},
        { name: '1WindowDayInd07'},
        { name: '2WindowStart07'},
        { name: '2WindowEnd07'},
        { name: '2WindowDayInd07'},
        { name: '3WindowStart07'},
        { name: '3WindowEnd07'},
        { name: '3WindowDayInd07'},
        { name: 'StdHoursPerDay01'},
        { name: 'StdHoursPerDay02'},
        { name: 'StdHoursPerDay03'},
        { name: 'MaxOTPerDay01'},
        { name: 'MaxOTPerDay02'},
        { name: 'MaxOTPerDay03'},
        { name: 'MaxHoursPerWeek01'},
        { name: 'MaxHoursPerWeek02'},
        { name: 'MaxHoursPerWeek03'},
        { name: 'StandardBreakTime01'},
        { name: 'StandardBreakTime02'},
        { name: 'StandardBreakTime03'},
        { name: 'PersonalDrivingTime01'},
        { name: 'PersonalDrivingTime02'},
        { name: 'PersonalDrivingTime03'},
        { name: 'AverageSickness01'},
        { name: 'AverageSickness02'},
        { name: 'AverageSickness03'},
        { name: 'AvgDrivingWorkDay01'},
        { name: 'AvgDrivingWorkDay02'},
        { name: 'AvgDrivingWorkDay03'},
        { name: 'ServiceCost'}

    ];

    constructor(injector: Injector) {
        super(injector);
        this.pageId = PageIdentifier.ICABSSBUSINESSMAINTENANCE;
    }

    ngOnInit(): void {
        super.ngOnInit();
    }
}
