export class AssignToData {
    // Static Properties
    public static readonly ASSIGNTO_DATA: Array<Object> = [
        { value: '1', text: 'Creating Employee' },
        { value: '2', text: 'Negotiating Employee' },
        { value: '3', text: 'Negotiating Employee - Specific Employee' },
        { value: '4', text: 'Negotiating Employee - Supervisor' },
        { value: '5', text: 'Servicing Branch - Regional Manager' },
        { value: '6', text: 'Servicing Branch - Branch Secretary' },
        { value: '7', text: 'Servicing Branch - Branch Manager' },
        { value: '8', text: 'Specific Employee' },
        { value: '9', text: 'Technician' },
        { value: '10', text: 'Technician - Specific Employee' },
        { value: '11', text: 'Technician - Supervisor' },
        { value: '12', text: 'Negotiating Branch - Regional Manager' },
        { value: '13', text: 'Negotiating Branch - Branch Manager' },
        { value: '14', text: 'Negotiating Branch - Branch Secretary' },
        { value: '15', text: 'Sales Employee' },
        { value: '16', text: 'Sales Employee - Specific Employee' },
        { value: '17', text: 'Sales Employee - Supervisor' },
        { value: '18', text: 'Specific Employee - Supervisor' },
        { value: '19', text: 'Team Administrator - Servicing Branch (Using Postcode)' },
        { value: '20', text: 'Team Administrator - Negotiating Branch (Using Postcode)' },
        { value: '21', text: 'Servicing Branch - Regional Manager (Using Postcode)' },
        { value: '22', text: 'Servicing Branch - Branch Secretary (Using Postcode)' },
        { value: '23', text: 'Servicing Branch - Branch Manager (Using Postcode)' },
        { value: '24', text: 'Negotiating Branch - Regional Manager (Using Postcode)' },
        { value: '25', text: 'Negotiating Branch - Branch Secretary (Using Postcode)' },
        { value: '26', text: 'Negotiating Branch - Branch Manager (Using Postcode)' },
        { value: '27', text: 'Sales Employee (Using Postcode)' },
        { value: '28', text: 'Sales Employee - Supervisor (Using Postcode)' },
        { value: '29', text: 'Team Administrator - Servicing Branch' },
        { value: '30', text: 'Team Administrator - Negotiating Branch' },
        { value: '31', text: 'Team Administrator - Servicing Branch - Supervisor (Using Postcode)' },
        { value: '32', text: 'Team Administrator - Negotiating Branch - Supervisor (Using Postcode)' },
        { value: '33', text: 'Team Administrator - Servicing Branch - Supervisor' },
        { value: '34', text: 'Team Administrator - Negotiating Branch - Supervisor' },
        { value: '35', text: 'Negotiating Employee (Using Postcode)' },
        { value: '36', text: 'Negotiating Employee - Specific Employee (Using Postcode)' },
        { value: '37', text: 'Negotiating Employee - Supervisor (Using Postcode)' },
        { value: '38', text: 'Sales Employee - Specific Employee (Using Postcode)' },
        { value: '39', text: 'Account Owner' },
        { value: '40', text: 'Account Owner - Supervisor' },
        { value: '41', text: 'Occupation - Negotiating Branch' },
        { value: '42', text: 'Occupation - Negotiating Branch - Supervisor' },
        { value: '43', text: 'Occupation - Servicing Branch' },
        { value: '44', text: 'Occupation - Servicing Branch - Supervisor' },
        { value: '45', text: 'Occupation - Negotiating Region' },
        { value: '46', text: 'Occupation - Negotiating Region - Supervisor' },
        { value: '47', text: 'Occupation - Servicing Region' },
        { value: '48', text: 'Occupation - Servicing Region - Supervisor' },
        { value: '49', text: 'Occupation - Business' },
        { value: '50', text: 'Occupation - Business - Supervisor' },
        { value: '51', text: 'Premises - Telesales Employee' },
        { value: '52', text: 'Premises - Telesales Employee - Supervisor' }
    ];
}
