import { BaseComponent } from './../../../../app/base/BaseComponent';
import { PageIdentifier } from './../../../../app/base/PageIdentifier';
import { Component, OnInit,Injector } from '@angular/core';
@Component({
    templateUrl: 'iCABSBBranchMaintenance.html'
})

export class BranchMaintenanceComponent extends BaseComponent implements OnInit {
    public pageId: string = '';
    public controls = [
        { name: 'BranchNumber'},
        { name: 'BranchName'},
        { name: 'BranchAddressLine1'},
        { name: 'BranchAddressLine2'},
        { name: 'BranchAddressLine3'},
        { name: 'BranchAddressLine4'},
        { name: 'BranchAddressLine5'},
        { name: 'BranchPostcode'},
        { name: 'GPSCoordinateX'},
        { name: 'GPSCoordinateY'},
        { name: 'RoutingGeonode'},
        { name: 'RoutingScore'},
        { name: 'SelRoutingSource'},
        { name: 'BranchVtxGeoCode'},
        { name: 'BranchManagerEmployeeCode'},
        { name: 'BranchManagerEmployeeSurname'},
        { name: 'BranchSecretaryEmployeeCode'},
        { name: 'BranchSecretaryEmployeeSurname'},
        { name: 'FBEVBranchServiceAreaCode'},
        { name: 'FBEVBranchServiceAreaDesc'},
        { name: 'BranchTelephone'},
        { name: 'BranchFax'},
        { name: 'BranchEmail'},
        { name: 'BranchInternalTelephone'},
        { name: 'BranchInternalSalesTelephone'},
        { name: 'BranchInternalServiceTelephone'},
        { name: 'ContactName'},
        { name: 'ContactPosition'},
        { name: 'ContactEmail'},
        { name: 'ServiceEmail'},
        { name: 'SalesEmail'},
        { name: 'NationalAccountBranch'},
        { name: 'LiveBranch'},
        { name: 'MailMergePrintAddress'},
        { name: 'DisablePostcodeChanges'},
        { name: 'EngineerRequiredInd'},
        { name: 'EnablePostCodeDefaulting'},
        { name: 'PropertyCareInd'},
        { name: 'ServiceAlignInd'},
        { name: 'EngineerServiceAreaCode'},
        { name: 'EngineerServiceAreaDesc'},
        { name: 'DOWBranchID'},
        { name: 'CostCentre'},
        { name: 'SMSCostCentre'},
        { name: 'OACostCentre'},
        { name: 'LanguageCode'},
        { name: 'LanguageDescription'},
        { name: 'LogoTypeCode'},
        { name: 'NextWasteConsignmentNoteNumber'},
        { name: 'WasteConsignmentNotePrefix'},
        { name: 'TaxAuthorityText'},
        { name: 'OutsideCityLimits'},
        { name: '1WindowStart01'},
        { name: '1WindowEnd01'},
        { name: '1WindowDayInd01'},
        { name: '2WindowStart01'},
        { name: '2WindowEnd01'},
        { name: '2WindowDayInd01'},
        { name: '3WindowStart01'},
        { name: '3WindowEnd01'},
        { name: '3WindowDayInd01'},
        { name: '1WindowStart02'},
        { name: '1WindowEnd02'},
        { name: '1WindowDayInd02'},
        { name: '2WindowStart02'},
        { name: '2WindowEnd02'},
        { name: '2WindowDayInd02'},
        { name: '3WindowStart02'},
        { name: '3WindowEnd02'},
        { name: '3WindowDayInd02'},
        { name: '1WindowStart03'},
        { name: '1WindowEnd03'},
        { name: '1WindowDayInd03'},
        { name: '2WindowStart03'},
        { name: '2WindowEnd03'},
        { name: '2WindowDayInd03'},
        { name: '3WindowStart03'},
        { name: '3WindowEnd03'},
        { name: '3WindowDayInd03'},
        { name: '1WindowStart04'},
        { name: '1WindowEnd04'},
        { name: '1WindowDayInd04'},
        { name: '2WindowStart04'},
        { name: '2WindowEnd04'},
        { name: '2WindowDayInd04'},
        { name: '3WindowStart04'},
        { name: '3WindowEnd04'},
        { name: '3WindowDayInd04'},
        { name: '1WindowStart05'},
        { name: '1WindowEnd05'},
        { name: '1WindowDayInd05'},
        { name: '2WindowStart05'},
        { name: '2WindowEnd05'},
        { name: '2WindowDayInd05'},
        { name: '3WindowStart05'},
        { name: '3WindowEnd05'},
        { name: '3WindowDayInd05'},
        { name: '1WindowStart06'},
        { name: '1WindowEnd06'},
        { name: '1WindowDayInd06'},
        { name: '2WindowStart06'},
        { name: '2WindowEnd06'},
        { name: '2WindowDayInd06'},
        { name: '3WindowStart06'},
        { name: '3WindowEnd06'},
        { name: '3WindowDayInd06'},
        { name: '1WindowStart07'},
        { name: '1WindowEnd07'},
        { name: '1WindowDayInd07'},
        { name: '2WindowStart07'},
        { name: '2WindowEnd07'},
        { name: '2WindowDayInd07'},
        { name: '3WindowStart07'},
        { name: '3WindowEnd07'},
        { name: '3WindowDayInd07'},
        { name: 'StdHoursPerDay01'},
        { name: 'StdHoursPerDay02'},
        { name: 'StdHoursPerDay03'},
        { name: 'MaxOTPerDay01'},
        { name: 'MaxOTPerDay02'},
        { name: 'MaxOTPerDay03'},
        { name: 'MaxHoursPerWeek01'},
        { name: 'MaxHoursPerWeek02'},
        { name: 'MaxHoursPerWeek03'},
        { name: 'StandardBreakTime01'},
        { name: 'StandardBreakTime02'},
        { name: 'StandardBreakTime03'},
        { name: 'PersonalDrivingTime01'},
        { name: 'PersonalDrivingTime02'},
        { name: 'PersonalDrivingTime03'},
        { name: 'AvgDrivingWorkDay01'},
        { name: 'AvgDrivingWorkDay02'},
        { name: 'AvgDrivingWorkDay03'},
        { name: 'AverageSickness01'},
        { name: 'AverageSickness02'},
        { name: 'AverageSickness03'}


    ];

    constructor(injector: Injector) {
        super(injector);
        this.pageId = PageIdentifier.ICABSBBRANCHMAINTENANCE;
    }

    ngOnInit(): void {
        super.ngOnInit();
    }
}
