export var ActionTypes = {
    SAVE_DATA_FROM: 'SAVE_DATA_FROM',
    CLEAR_DATA_FROM: 'CLEAR_DATA_FROM',
    SAVE_DATA_TO: 'SAVE_DATA_TO',
    CLEAR_DATA_TO: 'CLEAR_DATA_TO',
    SAVE_ACCOUNT_DATA: 'SAVE_ACCOUNT_DATA',
    CLEAR_ACCOUNT_DATA: 'CLEAR_ACCOUNT_DATA',
    SAVE_ACCOUNT_ROW_DATA: 'SAVE_ACCOUNT_ROW_DATA',
    CLEAR_ACCOUNT_ROW_DATA: 'CLEAR_ACCOUNT_ROW_DATA'
};
