export var ContactActionTypes = {
    SAVE_DATA: 'SAVE_DATA',
    SAVE_MODE: 'SAVE_MODE',
    SAVE_CODE: 'SAVE_CODE',
    SAVE_SYSCHAR: 'SAVE_SYSCHAR',
    SAVE_FIELD: 'SAVE_FIELD',
    SAVE_FIELD_PARAMS: 'SAVE_FIELD_PARAMS',
    SET_FORM_GROUPS: 'SET_FORM_GROUPS',
    SAVE_PARAMS: 'SAVE_PARAMS',
    VALIDATE_FORMS: 'VALIDATE_FORMS',
    CLEAR_DATA: 'CLEAR_DATA',
    CLEAR_ALL: 'CLEAR_ALL',
    SAVE_DATA_FROM_PARENT: 'SAVE_DATA_FROM_PARENT'
};
