export var GenericActionTypes = {
    SAVE_RECOMMENDATION_DATA: 'SAVE_DATA_FROM',
    CLEAR_RECOMMENDATION_DATA: 'CLEAR_DATA_FROM',
    SAVE_PRODUCT_SALES_DATA: 'SAVE_DATA_FROM',
    CLEAR_PRODUCT_SALES_DATA: 'CLEAR_DATA_FROM',
    SAVE_ADDRESS_CHANGE_DATA: 'SAVE_ADDRESS_CHANGE_DATA',
    CLEAR_ADDRESS_CHANGE_DATA: 'CLEAR_ADDRESS_CHANGE_DATA',
    SAVE_PREMISE_SERVICE_DATA: 'SAVE_PREMISE_SERVICE_DATA',
    CLEAR_PREMISE_SERVICE_DATA: 'CLEAR_PREMISE_SERVICE_DATA'
};
