export var ActionTypes = {
    SAVE_DATA: 'SAVE_DATA_FROM',
    CLEAR_DATA: 'CLEAR_DATA_FROM',
    SAVE_APPLY_API_CONTRACT_DATA: 'SAVE_APPLY_API_CONTRACT_DATA',
    CLEAR_APPLY_API_CONTRACT_DATA: 'CLEAR_APPLY_API_CONTRACT_DATA'
};
