export var ActionTypes = {
    SAVE_DATA: 'SAVE_DATA_FROM',
    CLEAR_DATA: 'CLEAR_DATA_FROM',
    SAVE_SYSTEM_PARAMETER: 'SAVE_SYSTEM_PARAMETER',
    CONTROL_DEFAULT_VALUE: 'CONTROL_DEFAULT_VALUE',
    RI_EXCHANGE: 'RI_EXCHANGE',
    EXCHANGE_METHOD: 'EXCHANGE_METHOD',
    FORM_CONTROLS: 'FORM_CONTROLS',
    PARENT_FORM: 'PARENT_FORM'
};
