/* TODO >>>
    Change the controls array below
*/

module.exports = function () {
    return controls = [
        { name: 'ContractNumber' },
        { name: 'ContractName' },
        { name: 'PremiseNumber' },
        { name: 'PremiseName' },
        { name: 'ProductCode' },
        { name: 'ProductDesc' },
        { name: 'PlanVisitNumber' },
        { name: 'PlanVisitNumber2' },
        { name: 'WasteConsignmentNoteNumber' },
        { name: 'EmployeeCode' },
        { name: 'EmployeeSurname' },
        { name: 'VehicleRegistration' },
        { name: 'AddEmployeeCode' },
        { name: 'AddEmployeeSurname' },
        { name: 'ServiceQuantity' },
        { name: 'UndeliveredQuantity' },
        { name: 'DeliveryQuantity' },
        { name: 'ServiceCoverItemNumber' },
        { name: 'ServiceCoverItemDesc' },
        { name: 'PremiseLocationNumber' },
        { name: 'ProductComponentCode' },
        { name: 'ProductComponentDesc' },
        { name: 'ServicedQuantity' },
        { name: 'ProductComponentRemoved' },
        { name: 'ProductComponentRemDesc' },
        { name: 'RemovalQuantity' },
        { name: 'InvoiceUnitValue' },
        { name: 'AdditionalChargeValue' },
        { name: 'SharedInd' },
        { name: 'PrepUsedInd' },
        { name: 'InfestationInd' },
        { name: 'WasteCollected' },
        { name: 'SignatureRecordedInd' },
        { name: 'StandardDuration' },
        { name: 'ServiceTimeStart' },
        { name: 'OvertimeDuration' },
        { name: 'ServiceTimeEnd' },
        { name: 'DeliveryNoteNumber' },
        { name: 'WEDSQty' },
        { name: 'WorkLoadIndexTotal' },
        { name: 'CustomerVisitRef' },
        { name: 'VisitReference' },
        { name: 'PremiseContactSignature' },
        { name: 'PremiseContactName' },
        { name: 'PremiseContactReason' },
        { name: 'ServiceVisitText' },
        { name: 'SafeToProceedInd' }
    ];
};